### ISSUE TITLE
 Missing preprocessed pre-training data 

### ISSUE THREAD

**Issue by kkkevinkkkkk** [thu-coai/PPT#1]
Hi, 

From the [link](https://drive.google.com/drive/folders/1Q6lMm48LcGZILQGI-0RaRJpLLQ_WX0gm?usp=sharing)  provided in section **2.2 Pretraining_data**, I only found folders of Downstram_data and pretrained_prompts. Did you put the preprocessed pre-training data in that folder?

Thanks!

**Comment by t1101675** [comment]
Hi, sorry for the delay in the response. We found that the pre-training data is too large to upload to google drive. Therefore, we provide a small version of our data: the processed data from 100M OpenWebText plain text. 

The *.bin files are the final data in the form that the model can read. The openwebtext.txt file is the original 100M data and the processed.txt file is the processed contexts and targets in the form that humans can read. In processed.txt, each line is a training sample and the context and target are split by \t\t .

You can get the full version of the data by moving the full OpenWebText plain texts to `PPT/pretrain_data/raw/openwebtext.txt` and running the script `PPT/scripts/tools/preprocess_pretrain_nss_uni.sh`.
