### ISSUE TITLE
pretrain时似乎无法从断点继续训练

### ISSUE THREAD

**Issue by John-Lin98** [thu-coai/PPT#10]
作者你好，我对你的方法很感兴趣，不过我在用你的代码重新pretrain一个pretrain-nss-uni prompt的时候发现经常训不到两个钟头训练就会自动中断，而且每次重新运行scripts/pretrain/pretrain_nss_uni.sh的时候都会重新开始训练，不知道是不是因为pretrain.py中缺少从断点继续训练的功能。
我训练时使用的是8张3090RTX，其它配置都与readme中的一致，每次中断都没有报错信息，都是进程自动终止，不知道训练自动中断是不是跟硬件有关。
![image](https://user-images.githubusercontent.com/65805703/199281205-d568ccfa-b78b-4d2a-8d21-9c8bd415c17c.png)
![image](https://user-images.githubusercontent.com/65805703/199281300-3f21f140-f7ca-4cd3-8a66-9dba96d5b399.png)

configuration in pretrain_nss_uni.sh：

```MP_SIZE=4

NUM_GPUS_PER_WORKER=8 # number of gpus used on one node
NUM_NODES=2

DATA_PATH="${WORKING_DIR}/pretrain_data/preprocessed/nss_uni_document"

CONFIG_PATH="${WORKING_DIR}/configs/model/t5_base_config.json"
CKPT_PATH="${WORKING_DIR}/checkpoints/t5-base/t5-MP4"

DS_CONFIG="${WORKING_DIR}/configs/deepspeed/ds_fp16.json"
TOKENIZER_PATH="${WORKING_DIR}/vocab_en"

PROMPT_CONFIG="${WORKING_DIR}/configs/prompt/pretrain.json"

MASTER_PORT=${1-1234}
BATCH_SIZE=16
GRAD_ACC=4
LR=0.1
TRAIN_ITER=200000

SAVE_PATH="${WORKING_DIR}/results/nss_uni_lr${LR}_G${GRAD_ACC}/"
LOG_FILE="${SAVE_PATH}/log.txt"

ENC_LEN=768
DEC_LEN=10
```

![image](https://user-images.githubusercontent.com/65805703/199295201-db1c262a-94e3-431e-b39b-d4b2ab3ea7a9.png)

希望作者能查看并解答这个issue，谢谢

**Comment by t1101675** [comment]
您好！感谢您对我们工作的关注！
程序中断应该是硬件有关，没有报错可能是内存爆了之类的原因。我们没有实现断点续跑的功能，一个简单的替代方案是加载之前存下的 prompt （相关代码可以参考 downstream task prompt tuning 的实现）。这样虽然没法保存 optimizer 的信息，但是根据我们之前预训练的经验，这对最后的结果影响不大。

**Comment by John-Lin98** [comment]
> 您好！感谢您对我们工作的关注！ 程序中断应该是硬件有关，没有报错可能是内存爆了之类的原因。我们没有实现断点续跑的功能，一个简单的替代方案是加载之前存下的 prompt （相关代码可以参考 downstream task prompt tuning 的实现）。这样虽然没法保存 optimizer 的信息，但是根据我们之前预训练的经验，这对最后的结果影响不大。

谢谢你的回复！
我猜测程序中断可能也跟内存不足有关，我打算之后换一个内存充足的机器环境再进行实验。我想问一下，使用T5-xxl预训练prompt时需要多大内存呢？
另外，我昨天的issue中忘记说明了一点，就是我在预训练prompt时使用的模型是T5-base而不是初始设置的T5-xxl，不知道这个对于预训练的结果和prompt的效果是否会有影响？

**Comment by t1101675** [comment]
我们没有记录内存的使用，但是印象中不会有太大的内存开销，和模型直接 fine-tune 的内存使用差不多。

使用 T5-base 预训练之后对比 T5-base prompt tuning 的结果应该会有提升，但是和 T5-xxl 相比可能会有差距。

**Comment by John-Lin98** [comment]
好的，谢谢你的解答！
