### ISSUE TITLE
KeyError when transfering checkpoints

### ISSUE THREAD

**Issue by lst356** [thu-coai/PPT#11]
Hi, I got this error when running _[python3 tools/transform.py --hf_path ${PATH_TO_PYTORCH_MODLE_BIN} --save_path "./checkpoints/t5-base" --half]_ in terminal. I download t5_base_model.bin. 
**KeyError:'encoder.block.12.layer.0.SelfAttention.q.weight'.** 
Could you give me some advice?

**Comment by t1101675** [comment]
t5 base model has only 12 layers. Maybe you should change the layer number at [this line](https://github.com/thu-coai/PPT/blob/dad6f2da91bc354999ba6ab8571b484417e3d0a1/tools/transform.py#L14) to 12.
